[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["HomeSer"]
known_django = ["django"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E265",  # Block comment should start with '# '
    "E402",  # Module level import not at top of file
    "E501",  # Line too long
    "F401",  # Module imported but unused
    "F403",  # 'from module import *' used; unable to detect undefined names
    "F405",  # Name may be undefined, or defined from star imports
    "F541",  # f-string is missing placeholders
    "F821",  # Undefined name
    "F841",  # Local variable is assigned to but never used
]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "migrations",
]