[tool.pytest.ini_options]
python_files = ["tests.py", "test_*.py", "*_tests.py"]
django_find_project = false
DJANGO_SETTINGS_MODULE = "HomeSer.settings"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["HomeSer"]
known_django = ["django"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E265", "E402", "E501", "F401", "F403", "F405", "F541", "F821", "F841"]
exclude = [".git", "__pycache__", "venv", ".venv", "migrations"]