# Generated by Django 5.2.5 on 2025-08-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HomeSer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING_PAYMENT",
                max_length=50,
            ),
        ),
    ]
