# Generated by Django 5.2.5 on 2025-08-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HomeSer", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
