# Generated by Django 5.2.5 on 2025-08-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSer', '0004_rename_homeser_car_user_id_64a233_idx_cart_user_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_cart_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_cart_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientprofile',
            name='clientprofile_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_order_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_service_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='service_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='service_avg_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='service_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_username_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_email_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDING_PAYMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
