# Generated by Django 5.2.5 on 2025-08-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomeSer", "0005_alter_user_options_remove_cart_cart_user_idx_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "service")},
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="HomeSer_car_user_id_64a233_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="HomeSer_car_cart_id_d0b853_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["service"], name="HomeSer_car_service_2325a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(fields=["user"], name="HomeSer_cli_user_id_396cf2_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="HomeSer_ord_user_id_d764b2_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="HomeSer_ord_created_f101d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="HomeSer_ord_status_5ad57e_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="HomeSer_ord_order_i_306645_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["service"], name="HomeSer_ord_service_ea7a45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="HomeSer_rev_user_id_ffb58f_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["service"], name="HomeSer_rev_service_db80b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="HomeSer_rev_rating_b514ce_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="HomeSer_rev_created_df8a91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["name"], name="HomeSer_ser_name_1558f2_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["average_rating"], name="HomeSer_ser_average_0c2d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["price"], name="HomeSer_ser_price_21deb2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="HomeSer_use_role_e88957_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="HomeSer_use_is_acti_ebe2c1_idx"
            ),
        ),
    ]
